<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class TestController extends Controller
{
    public function test()
    {
        return view('layout.master'); // TODO: Change the autogenerated stub
    }
    //
}
